/**
 * @copyright {@link https://github.com/JaapvanEkris/openrowingmonitor|OpenRowingMonitor}
 *
 * @file Tests of the Weighed Series object.
 */
// @vitest-environment node
import { test, assert, describe } from 'vitest'
import { createWeighedSeries } from './WeighedSeries.ts'

describe('Initialisation of the Weighed Series object', () => {
/**
 * @description Test behaviour for no datapoints
 */
  test('Series behaviour with an empty weighed series', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    testReliable(dataSeries, false)
    testLength(dataSeries, 0)
    testSeries(dataSeries, [])
    testatSeriesBegin(dataSeries, undefined)
    testAtSeriesEnd(dataSeries, undefined)
    testNumberOfValuesAbove(dataSeries, 0, undefined)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, undefined)
    testNumberOfValuesAbove(dataSeries, 10, undefined)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, undefined)
    testSum(dataSeries, undefined)
    testAverage(dataSeries, undefined)
    testReliableWeighted(dataSeries, false)
    testWeighedAverage(dataSeries, undefined)
    testMedian(dataSeries, undefined)
    testMinimum(dataSeries, undefined)
    testMaximum(dataSeries, undefined)
  })
})

describe('Test behaviour of the Weighed Series object when data is pushed', () => {
  /**
   * @description Test behaviour for a single datapoint
   */
  test('Series behaviour with a single pushed value. Series = [9]', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 1)
    testReliable(dataSeries, true)
    testLength(dataSeries, 1)
    testSeries(dataSeries, [9])
    testatSeriesBegin(dataSeries, 9)
    testAtSeriesEnd(dataSeries, 9)
    testNumberOfValuesAbove(dataSeries, 0, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 0)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 1)
    testSum(dataSeries, 9)
    testAverage(dataSeries, 9)
    testReliableWeighted(dataSeries, true)
    testWeighedAverage(dataSeries, 9)
    testMedian(dataSeries, 9)
    testMinimum(dataSeries, 9)
    testMaximum(dataSeries, 9)
  })

  test('Series behaviour with a second pushed value. Series = [9, 3]', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 1)
    dataSeries.push(3, 0)
    testReliable(dataSeries, true)
    testLength(dataSeries, 2)
    testSeries(dataSeries, [9, 3])
    testatSeriesBegin(dataSeries, 9)
    testAtSeriesEnd(dataSeries, 3)
    testNumberOfValuesAbove(dataSeries, 0, 2)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 0)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 12)
    testAverage(dataSeries, 6)
    testReliableWeighted(dataSeries, true)
    testWeighedAverage(dataSeries, 9)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 9)
  })

  test('Series behaviour with a third pushed value. Series = [9, 3, 6]', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 1)
    dataSeries.push(3, 0)
    dataSeries.push(6, 1)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [9, 3, 6])
    testatSeriesBegin(dataSeries, 9)
    testAtSeriesEnd(dataSeries, 6)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 0)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 3)
    testSum(dataSeries, 18)
    testAverage(dataSeries, 6)
    testReliableWeighted(dataSeries, true)
    testWeighedAverage(dataSeries, 7.5)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 9)
  })
})

describe('Test behaviour of the Weighed Series object when data is pushed out again', () => {
  /**
   * @description Test behaviour for a single datapoint
   */
  test('Series behaviour with a fourth pushed value and varying weights. Series = [3, 6, 12]', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 0)
    dataSeries.push(3, 0)
    dataSeries.push(6, 1)
    dataSeries.push(12, 1)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testReliableWeighted(dataSeries, true)
    testWeighedAverage(dataSeries, 9)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
  })

  test('Series behaviour with a fifth pushed value and different weights. Series = [6, 12, -3]', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 1)
    dataSeries.push(3, 1)
    dataSeries.push(6, 1)
    dataSeries.push(12, 1)
    dataSeries.push(-3, 0.5)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [6, 12, -3])
    testatSeriesBegin(dataSeries, 6)
    testAtSeriesEnd(dataSeries, -3)
    testNumberOfValuesAbove(dataSeries, 0, 2)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 1)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 15)
    testAverage(dataSeries, 5)
    testReliableWeighted(dataSeries, true)
    testWeighedAverage(dataSeries, 6.6)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, -3)
    testMaximum(dataSeries, 12)
  })

  test('Series behaviour pushing out the min and max value and forcing a recalculate of min/max via the array.', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 1)
    dataSeries.push(3, 1)
    dataSeries.push(6, 1)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 9)
    dataSeries.push(6, 1)
    testLength(dataSeries, 3)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 6)
    dataSeries.push(6, 1)
    testLength(dataSeries, 3)
    testMinimum(dataSeries, 6)
    testMaximum(dataSeries, 6)
  })

  test('Series behaviour pushing out the min and max value, replacing them just in time.', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 1)
    dataSeries.push(3, 1)
    dataSeries.push(6, 1)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 9)
    dataSeries.push(12, 1)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
    dataSeries.push(1, 1)
    testMinimum(dataSeries, 1)
    testMaximum(dataSeries, 12)
  })
})

describe('Test Edge cases of the Weighed Series', () => {
  /**
   * @description Test behaviour for a single datapoint
   */
  test('Edge_01: Series behaviour when only 0-weighted values are inserted', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 0)
    dataSeries.push(3, 0)
    dataSeries.push(6, 0)
    dataSeries.push(12, 0)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testReliableWeighted(dataSeries, false)
    testWeighedAverage(dataSeries, undefined)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
  })

  test('Edge_02: Series behaviour when only 0-weighted values are inserted after a valid start', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 0)
    dataSeries.push(3, 0)
    dataSeries.push(6, 1)
    dataSeries.push(12, 1)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testWeighedAverage(dataSeries, 9)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
    dataSeries.push(9, 0)
    dataSeries.push(3, 0)
    dataSeries.push(6, 0)
    dataSeries.push(12, 0)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testReliableWeighted(dataSeries, false)
    testWeighedAverage(dataSeries, undefined)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
  })

  test('Edge_03: Series behaviour when only 0-weighted values are inserted after a valid start, with different default value', () => {
    const dataSeries = createWeighedSeries(3, 14)
    testReliable(dataSeries, false)
    testLength(dataSeries, 0)
    testSeries(dataSeries, [])
    testatSeriesBegin(dataSeries, undefined)
    testAtSeriesEnd(dataSeries, undefined)
    testNumberOfValuesAbove(dataSeries, 0, undefined)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, undefined)
    testNumberOfValuesAbove(dataSeries, 10, undefined)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, undefined)
    testSum(dataSeries, undefined)
    testAverage(dataSeries, 14)
    testReliableWeighted(dataSeries, false)
    testWeighedAverage(dataSeries, 14)
    testMedian(dataSeries, undefined)
    testMinimum(dataSeries, undefined)
    testMaximum(dataSeries, undefined)
    dataSeries.push(9, 0)
    dataSeries.push(3, 0)
    dataSeries.push(6, 1)
    dataSeries.push(12, 1)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testReliableWeighted(dataSeries, true)
    testWeighedAverage(dataSeries, 9)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
    dataSeries.push(9, 0)
    dataSeries.push(3, 0)
    dataSeries.push(6, 0)
    dataSeries.push(12, 0)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testReliableWeighted(dataSeries, false)
    testWeighedAverage(dataSeries, 14)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
  })

  test('Edge_04: Series behaviour when undefined values are inserted at the start', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(undefined, 1)
    dataSeries.push(3, undefined)
    dataSeries.push(undefined, 1)
    dataSeries.push(12, undefined)
    testReliable(dataSeries, false)
    testLength(dataSeries, 0)
    testSeries(dataSeries, [])
    testatSeriesBegin(dataSeries, undefined)
    testAtSeriesEnd(dataSeries, undefined)
    testNumberOfValuesAbove(dataSeries, 0, undefined)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, undefined)
    testNumberOfValuesAbove(dataSeries, 10, undefined)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, undefined)
    testSum(dataSeries, undefined)
    testAverage(dataSeries, undefined)
    testReliableWeighted(dataSeries, false)
    testWeighedAverage(dataSeries, undefined)
    testMedian(dataSeries, undefined)
    testMinimum(dataSeries, undefined)
    testMaximum(dataSeries, undefined)
  })

  test('Edge_05: Series behaviour when undefined values are inserted after some valid points', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 1)
    dataSeries.push(3, 1)
    dataSeries.push(6, 1)
    dataSeries.push(12, 1)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testWeighedAverage(dataSeries, 7)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
    dataSeries.push(undefined, 1)
    dataSeries.push(undefined, 1)
    dataSeries.push(undefined, 1)
    dataSeries.push(undefined, 1)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testReliableWeighted(dataSeries, true)
    testWeighedAverage(dataSeries, 7)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
  })

  test('Edge_06: Series behaviour when undefined-weighted values are inserted', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 1)
    dataSeries.push(3, 1)
    dataSeries.push(6, 1)
    dataSeries.push(12, 1)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testReliableWeighted(dataSeries, true)
    testWeighedAverage(dataSeries, 7)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
    dataSeries.push(1, undefined)
    dataSeries.push(2, undefined)
    dataSeries.push(4, undefined)
    dataSeries.push(8, undefined)
    testReliable(dataSeries, true)
    testLength(dataSeries, 3)
    testSeries(dataSeries, [3, 6, 12])
    testatSeriesBegin(dataSeries, 3)
    testAtSeriesEnd(dataSeries, 12)
    testNumberOfValuesAbove(dataSeries, 0, 3)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, 0)
    testNumberOfValuesAbove(dataSeries, 10, 1)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, 2)
    testSum(dataSeries, 21)
    testAverage(dataSeries, 7)
    testReliableWeighted(dataSeries, true)
    testWeighedAverage(dataSeries, 7)
    testMedian(dataSeries, 6)
    testMinimum(dataSeries, 3)
    testMaximum(dataSeries, 12)
  })

})

describe('Test behaviour of the Weighed Series object when reset', () => {
  /**
   * @description Test behaviour for a single datapoint
   */
  test('Series behaviour with a five pushed values followed by a reset, Series = []', () => {
    const dataSeries = createWeighedSeries(3, undefined)
    dataSeries.push(9, 1)
    dataSeries.push(3, 1)
    dataSeries.push(6, 1)
    dataSeries.push(12, 1)
    dataSeries.push(-3, 1)
    testSeries(dataSeries, [6, 12, -3])
    dataSeries.reset()
    testLength(dataSeries, 0)
    testatSeriesBegin(dataSeries, undefined)
    testAtSeriesEnd(dataSeries, undefined)
    testNumberOfValuesAbove(dataSeries, 0, undefined)
    testNumberOfValuesEqualOrBelow(dataSeries, 0, undefined)
    testNumberOfValuesAbove(dataSeries, 10, undefined)
    testNumberOfValuesEqualOrBelow(dataSeries, 10, undefined)
    testSum(dataSeries, undefined)
    testAverage(dataSeries, undefined)
    testWeighedAverage(dataSeries, undefined)
    testMedian(dataSeries, undefined)
  })
})

function testLength (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.length(), expectedValue, `Expected length should be ${expectedValue}, encountered ${series.length()}`)
}

function testSeries (series: Readonly<WeighedSeries>, expectedValue: number[]) {
  assert.strictEqual(series.series().toString(), expectedValue.toString(), `Expected series to be ${expectedValue}, encountered ${series.series()}`)
}

function testatSeriesBegin (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.atSeriesBegin(), expectedValue, `Expected atSeriesBegin to be ${expectedValue}, encountered ${series.atSeriesBegin()}`)
}

function testAtSeriesEnd (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.atSeriesEnd(), expectedValue, `Expected atSeriesEnd to be ${expectedValue}, encountered ${series.atSeriesEnd()}`)
}

function testNumberOfValuesAbove (series: Readonly<WeighedSeries>, cutoff: Readonly<number>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.numberOfValuesAbove(cutoff), expectedValue, `Expected numberOfValuesAbove(${cutoff}) to be ${expectedValue}, encountered ${series.numberOfValuesAbove(cutoff)}`)
}

function testNumberOfValuesEqualOrBelow (series: Readonly<WeighedSeries>, cutoff: Readonly<number>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.numberOfValuesEqualOrBelow(cutoff), expectedValue, `Expected numberOfValuesEqualOrBelow(${cutoff}) to be ${expectedValue}, encountered ${series.numberOfValuesEqualOrBelow(cutoff)}`)
}

function testSum (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.sum(), expectedValue, `Expected sum to be ${expectedValue}, encountered ${series.sum()}`)
}

function testAverage (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.average(), expectedValue, `Expected average to be ${expectedValue}, encountered ${series.average()}`)
}

function testWeighedAverage (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.weighedAverage(), expectedValue, `Expected weighedAverage to be ${expectedValue}, encountered ${series.weighedAverage()}`)
}

function testMedian (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.median(), expectedValue, `Expected median to be ${expectedValue}, encountered ${series.median()}`)
}

function testMinimum (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.minimum(), expectedValue, `Expected minimum to be ${expectedValue}, encountered ${series.minimum()}`)
}

function testMaximum (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.maximum(), expectedValue, `Expected maximum to be ${expectedValue}, encountered ${series.maximum()}`)
}

function testReliable (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.reliable(), expectedValue, `Expected reliable to be ${expectedValue}, encountered ${series.reliable()}`)
}

function testReliableWeighted (series: Readonly<WeighedSeries>, expectedValue: Readonly<number>) {
  assert.strictEqual(series.reliableWeighted(), expectedValue, `Expected reliable to be ${expectedValue}, encountered ${series.reliableWeighted()}`)
}
